### ISSUE TITLE
No module named six

### ISSUE THREAD

**Issue by mbl-35** [byackee/jarvis-rivescript#3]
Juste pour les suivants, j'ai rencontré une erreur lors de l'utilisation du plugin installé directement depuis l'interface de jarvis.sh.

`Traceback (most recent call last):
  File "./plugins/jarvis-rivescript/rivescriptfr.py", line 4, in <module>
    from rivescript import RiveScript
  File "/home/sysres/jarvis/plugins/jarvis-rivescript/rivescript/__init__.py", line 25, in <module>
    from .rivescript import RiveScript
  File "/home/sysres/jarvis/plugins/jarvis-rivescript/rivescript/rivescript.py", line 9, in <module>
    from six import text_type
ImportError: No module named six
`

Informations: Ubuntu 16.04.1 LTS sur Raspberry 2

Il faut simplement installer le module au niveau des librairies python:
`
sudo pip install six
`

**Comment by byackee** [comment]
Bonjour,

Merci, j'ai ajouté la commande au fichier install.sh
